#alias ls='ls --color=auto'
alias ls='lsd --icon=never --classify'
alias ll='lsd --long --header'
alias grep='grep --color=auto --binary-files=without-match'
alias mkdir='mkdir -p'
alias ps='ps aux'
alias topcpu='/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -n10'
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias fgrep='fgrep --color=auto --binary-files=without-match'
alias egrep='egrep --color=auto --binary-files=without-match'
alias cd..='cd ..'
alias locate='locate -i'
alias df='df -h'
alias duall='du -sh * | sort -h'
alias docker_ls_dangling='docker images --filter "dangling=true"'
alias docker_rm_dangling='docker rmi $(docker images -q --filter "dangling=true")'
