alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -lh'
alias cd..='cd ..'
alias locate='locate -i'
alias df='df -h'
alias duall='du -sh * | sort -h'

alias sysinfo='uname -a && echo "" && cat /etc/os-release && echo "" && lsb_release -a'
alias sysinfo_mac='uname -a && echo "" && sw_vers'
