alias ls='ls --color=auto'
alias dmesg='sudo dmesg -HL'
alias grep='grep --color=auto --binary-files=without-match'
alias fgrep='fgrep --color=auto --binary-files=without-match'
alias egrep='egrep --color=auto --binary-files=without-match'
alias ll='ls -lh'
alias cd..='cd ..'
alias locate='locate -i'
alias df='df -h'
alias duall='du -sh * | sort -h'
alias docker_ls_dangling='docker images --filter "dangling=true"'
alias docker_rm_dangling='docker rmi $(docker images -q --filter "dangling=true")'
